# frozen_string_literal: true

source 'https://rubygems.org'

gem 'blabla'
gem 'cpf_faker'
gem 'faker'
gem 'factory_bot'
gem 'httparty'
gem 'rspec'
gem 'rake'
gem 'rspec_junit_formatter'
gem 'tiny_tds'
gem 'dotenv'
